ALTER TABLE `Business` ADD COLUMN `memberId` VARCHAR(191) NULL;

ALTER TABLE `Business` ADD COLUMN `descriptionGu` TEXT NULL;

ALTER TABLE `Business` ADD COLUMN `whatsapp` VARCHAR(191) NULL;

ALTER TABLE `Business` ADD COLUMN `email` VARCHAR(191) NULL;

ALTER TABLE `Business` ADD COLUMN `addressGu` TEXT NULL;

ALTER TABLE `Business` ADD COLUMN `estd` VARCHAR(191) NULL;

ALTER TABLE `Business` ADD COLUMN `mapUrl` TEXT NULL;

ALTER TABLE `Business` ADD COLUMN `logoUrl` TEXT NULL;

ALTER TABLE `Business` ADD COLUMN `instagram` VARCHAR(191) NULL;

ALTER TABLE `Business` ADD COLUMN `facebook` VARCHAR(191) NULL;

ALTER TABLE `Business` ADD COLUMN `youtube` VARCHAR(191) NULL;